'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34011
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("BOCommissionReport.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iAmt_paid.
        '''</summary>
        Friend ReadOnly Property Param_iAmt_paid() As String
            Get
                Return ResourceManager.GetString("Param_iAmt_paid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iBatchID.
        '''</summary>
        Friend ReadOnly Property Param_iBatchID() As String
            Get
                Return ResourceManager.GetString("Param_iBatchID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iBill_to_state.
        '''</summary>
        Friend ReadOnly Property Param_iBill_to_state() As String
            Get
                Return ResourceManager.GetString("Param_iBill_to_state", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iComm_amt.
        '''</summary>
        Friend ReadOnly Property Param_iComm_amt() As String
            Get
                Return ResourceManager.GetString("Param_iComm_amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iComm_prct.
        '''</summary>
        Friend ReadOnly Property Param_iComm_prct() As String
            Get
                Return ResourceManager.GetString("Param_iComm_prct", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to icommdate.
        '''</summary>
        Friend ReadOnly Property Param_iCommDate() As String
            Get
                Return ResourceManager.GetString("Param_iCommDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to icommdraftid.
        '''</summary>
        Friend ReadOnly Property Param_icommdraftid() As String
            Get
                Return ResourceManager.GetString("Param_icommdraftid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to icommdraftid_deleted.
        '''</summary>
        Friend ReadOnly Property Param_icommdraftid_deleted() As String
            Get
                Return ResourceManager.GetString("Param_icommdraftid_deleted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCommID.
        '''</summary>
        Friend ReadOnly Property Param_iCommID() As String
            Get
                Return ResourceManager.GetString("Param_iCommID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iCusNo.
        '''</summary>
        Friend ReadOnly Property Param_iCusNo() As String
            Get
                Return ResourceManager.GetString("Param_iCusNo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to idatasource.
        '''</summary>
        Friend ReadOnly Property Param_idatasource() As String
            Get
                Return ResourceManager.GetString("Param_idatasource", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iDisc_amt.
        '''</summary>
        Friend ReadOnly Property Param_iDisc_amt() As String
            Get
                Return ResourceManager.GetString("Param_iDisc_amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iDraftID.
        '''</summary>
        Friend ReadOnly Property Param_iDraftID() As String
            Get
                Return ResourceManager.GetString("Param_iDraftID", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iDraftName.
        '''</summary>
        Friend ReadOnly Property Param_iDraftName() As String
            Get
                Return ResourceManager.GetString("Param_iDraftName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iDraftOrFinal.
        '''</summary>
        Friend ReadOnly Property Param_iDraftOrFinal() As String
            Get
                Return ResourceManager.GetString("Param_iDraftOrFinal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iFrt_amt.
        '''</summary>
        Friend ReadOnly Property Param_iFrt_amt() As String
            Get
                Return ResourceManager.GetString("Param_iFrt_amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iFrt_prcnt.
        '''</summary>
        Friend ReadOnly Property Param_iFrt_prcnt() As String
            Get
                Return ResourceManager.GetString("Param_iFrt_prcnt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iInv_no.
        '''</summary>
        Friend ReadOnly Property Param_iInv_no() As String
            Get
                Return ResourceManager.GetString("Param_iInv_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iMisc_amt.
        '''</summary>
        Friend ReadOnly Property Param_iMisc_amt() As String
            Get
                Return ResourceManager.GetString("Param_iMisc_amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to imodified.
        '''</summary>
        Friend ReadOnly Property Param_imodified() As String
            Get
                Return ResourceManager.GetString("Param_imodified", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iNet_sls_amt.
        '''</summary>
        Friend ReadOnly Property Param_iNet_sls_amt() As String
            Get
                Return ResourceManager.GetString("Param_iNet_sls_amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iord_no.
        '''</summary>
        Friend ReadOnly Property Param_iord_no() As String
            Get
                Return ResourceManager.GetString("Param_iord_no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iOrder_dt.
        '''</summary>
        Friend ReadOnly Property Param_iOrder_dt() As String
            Get
                Return ResourceManager.GetString("Param_iOrder_dt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iorderno.
        '''</summary>
        Friend ReadOnly Property Param_iorderno() As String
            Get
                Return ResourceManager.GetString("Param_iorderno", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPickup_allow_amt.
        '''</summary>
        Friend ReadOnly Property Param_iPickup_allow_amt() As String
            Get
                Return ResourceManager.GetString("Param_iPickup_allow_amt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iPymt_dt.
        '''</summary>
        Friend ReadOnly Property Param_iPymt_dt() As String
            Get
                Return ResourceManager.GetString("Param_iPymt_dt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iReference.
        '''</summary>
        Friend ReadOnly Property Param_iReference() As String
            Get
                Return ResourceManager.GetString("Param_iReference", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iRep_group.
        '''</summary>
        Friend ReadOnly Property Param_iRep_group() As String
            Get
                Return ResourceManager.GetString("Param_iRep_group", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iRowState.
        '''</summary>
        Friend ReadOnly Property Param_iRowState() As String
            Get
                Return ResourceManager.GetString("Param_iRowState", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iShip_dt.
        '''</summary>
        Friend ReadOnly Property Param_iShip_dt() As String
            Get
                Return ResourceManager.GetString("Param_iShip_dt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iShip_to_name.
        '''</summary>
        Friend ReadOnly Property Param_iShip_to_name() As String
            Get
                Return ResourceManager.GetString("Param_iShip_to_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iShip_to_state.
        '''</summary>
        Friend ReadOnly Property Param_iShip_to_state() As String
            Get
                Return ResourceManager.GetString("Param_iShip_to_state", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSlspsn_name.
        '''</summary>
        Friend ReadOnly Property Param_iSlspsn_name() As String
            Get
                Return ResourceManager.GetString("Param_iSlspsn_name", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSlspsn_number.
        '''</summary>
        Friend ReadOnly Property Param_iSlspsn_number() As String
            Get
                Return ResourceManager.GetString("Param_iSlspsn_number", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iSS12.
        '''</summary>
        Friend ReadOnly Property Param_iSs12() As String
            Get
                Return ResourceManager.GetString("Param_iSs12", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to itotalsalesamt.
        '''</summary>
        Friend ReadOnly Property Param_iTotalSalesAmt() As String
            Get
                Return ResourceManager.GetString("Param_iTotalSalesAmt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iUSAorCAN.
        '''</summary>
        Friend ReadOnly Property Param_iUSAorCAN() As String
            Get
                Return ResourceManager.GetString("Param_iUSAorCAN", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iUser_dt.
        '''</summary>
        Friend ReadOnly Property Param_iUserDate() As String
            Get
                Return ResourceManager.GetString("Param_iUserDate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to iUser_name.
        '''</summary>
        Friend ReadOnly Property Param_iUserName() As String
            Get
                Return ResourceManager.GetString("Param_iUserName", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ivalid_comm.
        '''</summary>
        Friend ReadOnly Property Param_ivalid_comm() As String
            Get
                Return ResourceManager.GetString("Param_ivalid_comm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to odraftid.
        '''</summary>
        Friend ReadOnly Property Param_odraftid() As String
            Get
                Return ResourceManager.GetString("Param_odraftid", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spARGetCommHeaderList.
        '''</summary>
        Friend ReadOnly Property SP_spARGetCommHeaderList() As String
            Get
                Return ResourceManager.GetString("SP_spARGetCommHeaderList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spARGetCommissionReport_MAZ.
        '''</summary>
        Friend ReadOnly Property SP_spARGetCommissionReport_MAZ() As String
            Get
                Return ResourceManager.GetString("SP_spARGetCommissionReport_MAZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spARSaveCommission_MAZ.
        '''</summary>
        Friend ReadOnly Property SP_spARSaveCommission_MAZ() As String
            Get
                Return ResourceManager.GetString("SP_spARSaveCommission_MAZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spARSaveFinalDraftCommission_MAZ.
        '''</summary>
        Friend ReadOnly Property SP_spARSaveFinalDraftCommission_MAZ() As String
            Get
                Return ResourceManager.GetString("SP_spARSaveFinalDraftCommission_MAZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spARSaveFinalDraftHdr_MAZ.
        '''</summary>
        Friend ReadOnly Property SP_spARSaveFinalDraftHdr_MAZ() As String
            Get
                Return ResourceManager.GetString("SP_spARSaveFinalDraftHdr_MAZ", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to spOEGetOrderCommissionReport_MAZ.
        '''</summary>
        Friend ReadOnly Property SP_spOEGetOrderCommissionReport_MAZ() As String
            Get
                Return ResourceManager.GetString("SP_spOEGetOrderCommissionReport_MAZ", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
