'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=LEHIGH-GA;Initial Catalog=DATA;Persist Security Info=True;User ID=sa;"& _ 
            "Password=sa")>  _
        Public ReadOnly Property DATAConnectionString() As String
            Get
                Return CType(Me("DATAConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MASS_SQL;Initial Catalog=DATA_999;Persist Security Info=True;User ID="& _ 
            "sa;Password=stmartin")>  _
        Public ReadOnly Property DATA999ConnectionString() As String
            Get
                Return CType(Me("DATA999ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MASS_SQL2;Initial Catalog=DATA;Persist Security Info=True;User ID=sa;"& _ 
            "Password=STMARTIN")>  _
        Public ReadOnly Property DATAMASSConnection() As String
            Get
                Return CType(Me("DATAMASSConnection"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BatchID_Stripped() As Boolean
            Get
                Return CType(Me("BatchID_Stripped"),Boolean)
            End Get
            Set
                Me("BatchID_Stripped") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property TotalSalesAmt() As Boolean
            Get
                Return CType(Me("TotalSalesAmt"),Boolean)
            End Get
            Set
                Me("TotalSalesAmt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property RepGroup() As Boolean
            Get
                Return CType(Me("RepGroup"),Boolean)
            End Get
            Set
                Me("RepGroup") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SalesPersonNumber() As Boolean
            Get
                Return CType(Me("SalesPersonNumber"),Boolean)
            End Get
            Set
                Me("SalesPersonNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property InvoiceNumber() As Boolean
            Get
                Return CType(Me("InvoiceNumber"),Boolean)
            End Get
            Set
                Me("InvoiceNumber") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CusNo() As Boolean
            Get
                Return CType(Me("CusNo"),Boolean)
            End Get
            Set
                Me("CusNo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShipToName() As Boolean
            Get
                Return CType(Me("ShipToName"),Boolean)
            End Get
            Set
                Me("ShipToName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ShipToState() As Boolean
            Get
                Return CType(Me("ShipToState"),Boolean)
            End Get
            Set
                Me("ShipToState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FreightAmount() As Boolean
            Get
                Return CType(Me("FreightAmount"),Boolean)
            End Get
            Set
                Me("FreightAmount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property FreightPercent() As Boolean
            Get
                Return CType(Me("FreightPercent"),Boolean)
            End Get
            Set
                Me("FreightPercent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property NetSalesAmount() As Boolean
            Get
                Return CType(Me("NetSalesAmount"),Boolean)
            End Get
            Set
                Me("NetSalesAmount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property DiscountAmount() As Boolean
            Get
                Return CType(Me("DiscountAmount"),Boolean)
            End Get
            Set
                Me("DiscountAmount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property PickupAllowanceAmount() As Boolean
            Get
                Return CType(Me("PickupAllowanceAmount"),Boolean)
            End Get
            Set
                Me("PickupAllowanceAmount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property AmountPaid() As Boolean
            Get
                Return CType(Me("AmountPaid"),Boolean)
            End Get
            Set
                Me("AmountPaid") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CommissionPercent() As Boolean
            Get
                Return CType(Me("CommissionPercent"),Boolean)
            End Get
            Set
                Me("CommissionPercent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property CommissionAmount() As Boolean
            Get
                Return CType(Me("CommissionAmount"),Boolean)
            End Get
            Set
                Me("CommissionAmount") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Reference() As Boolean
            Get
                Return CType(Me("Reference"),Boolean)
            End Get
            Set
                Me("Reference") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SalesPersonName() As Boolean
            Get
                Return CType(Me("SalesPersonName"),Boolean)
            End Get
            Set
                Me("SalesPersonName") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BillToState() As Boolean
            Get
                Return CType(Me("BillToState"),Boolean)
            End Get
            Set
                Me("BillToState") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property OrderDate() As Boolean
            Get
                Return CType(Me("OrderDate"),Boolean)
            End Get
            Set
                Me("OrderDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ShipDate() As Boolean
            Get
                Return CType(Me("ShipDate"),Boolean)
            End Get
            Set
                Me("ShipDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property PaymentDate() As Boolean
            Get
                Return CType(Me("PaymentDate"),Boolean)
            End Get
            Set
                Me("PaymentDate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SS12() As Boolean
            Get
                Return CType(Me("SS12"),Boolean)
            End Get
            Set
                Me("SS12") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property Modified() As Boolean
            Get
                Return CType(Me("Modified"),Boolean)
            End Get
            Set
                Me("Modified") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property BatchID() As Boolean
            Get
                Return CType(Me("BatchID"),Boolean)
            End Get
            Set
                Me("BatchID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property CusNo_Stripped() As Boolean
            Get
                Return CType(Me("CusNo_Stripped"),Boolean)
            End Get
            Set
                Me("CusNo_Stripped") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MASS_SQL;Initial Catalog=DATA_200;Persist Security Info=True;User ID="& _ 
            "sa;Password=stmartin")>  _
        Public ReadOnly Property DATA200ConnectionString() As String
            Get
                Return CType(Me("DATA200ConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property OrderNo() As Boolean
            Get
                Return CType(Me("OrderNo"),Boolean)
            End Get
            Set
                Me("OrderNo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property MiscAmt() As Boolean
            Get
                Return CType(Me("MiscAmt"),Boolean)
            End Get
            Set
                Me("MiscAmt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property ValidatedComm() As Boolean
            Get
                Return CType(Me("ValidatedComm"),Boolean)
            End Get
            Set
                Me("ValidatedComm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property AddedColumn() As Boolean
            Get
                Return CType(Me("AddedColumn"),Boolean)
            End Get
            Set
                Me("AddedColumn") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TC-OPTIPLEX\SQL2008R2;Initial Catalog=DATA;Persist Security Info=True"& _ 
            ";User ID=sa;Password=230South5th")>  _
        Public ReadOnly Property DATA_TCOPTIPLEX() As String
            Get
                Return CType(Me("DATA_TCOPTIPLEX"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=MASS_SQL2;Initial Catalog=DATA;Persist Security Info=True;User ID=sa;"& _ 
            "Password=STMARTIN")>  _
        Public ReadOnly Property DATA_MASSSQL2() As String
            Get
                Return CType(Me("DATA_MASSSQL2"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=TC-OPTIPLEX;Initial Catalog=DATA03;Persist Security Info=True;User ID"& _ 
            "=sa;Password=230South5th")>  _
        Public ReadOnly Property DATA03_TCOptiPlex() As String
            Get
                Return CType(Me("DATA03_TCOptiPlex"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mass-sql1")>  _
        Public ReadOnly Property DefaultServer() As String
            Get
                Return CType(Me("DefaultServer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DATA")>  _
        Public Property DefaultDB() As String
            Get
                Return CType(Me("DefaultDB"),String)
            End Get
            Set
                Me("DefaultDB") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.MassarelliCommissionReport.My.MySettings
            Get
                Return Global.MassarelliCommissionReport.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
